DROP TABLE IF EXISTS TIENDA;
CREATE TABLE  "TIENDA" (
);


DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE  "USUARIOS" (
);

DROP TABLE IF EXISTS COMPRAS;
CREATE TABLE  "COMPRAS" (
);

DROP TABLE IF EXISTS OBJETOS;
CREATE TABLE  "OBJETOS" (
);

DROP TABLE IF EXISTS OPINIONES;
CREATE TABLE  "OPINIONES" (
);
