DROP TABLE IF EXISTS TIENDA;
CREATE TABLE  "TIENDA" (
    "OBJETO_ID" INTEGER NOT NULL PRIMARY KEY,
    "NOMBRE_OBJETO" VARCHAR(100) NOT NULL,
    "PRECIO" NUMERIC NOT NULL,
    "CANTIDAD" INTEGER NOT NULL
);


DROP TABLE IF EXISTS USUARIO;
CREATE TABLE  "USUARIO" (
    "NOMBRE_USUARIO" VARCHAR(100) NOT NULL PRIMARY KEY,
    "CONTRASENYA" VARCHAR(100) NOT NULL,
    "CORREO" VARCHAR(100) NOT NULL,
    "ADMIN" BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS COMPRA;
CREATE TABLE  "COMPRA" (
    "COMPRA_ID" INTEGER NOT NULL PRIMARY KEY,
    "NOMBRE_USUARIO" VARCHAR(100) NOT NULL,
    "NOMBRE_OBJETO" VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS OBJETO;
CREATE TABLE  "OBJETO" (
    "NOMBRE_OBJETO" VARCHAR(100) NOT NULL PRIMARY KEY,
    "DESCRIPCION" VARCHAR(200) NULL
);

DROP TABLE IF EXISTS OPINION;
CREATE TABLE  "OPINION" (
    "OPINION_ID" INTEGER NOT NULL PRIMARY KEY,
    "TEXTO" VARCHAR(500) NOT NULL
);
